# Generated by Django 3.1.2 on 2020-12-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='')),
                ('Owner', models.CharField(max_length=500)),
                ('Comments', models.JSONField()),
                ('date', models.DateTimeField()),
                ('likes', models.JSONField()),
                ('saved', models.JSONField()),
                ('Caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=500)),
                ('Second_name', models.CharField(max_length=500)),
                ('Username', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('Verified', models.BooleanField(default=False)),
                ('Bio', models.TextField()),
                ('Notifications', models.JSONField()),
            ],
        ),
    ]
