# Generated by Django 3.1.4 on 2020-12-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkxmain', '0002_auto_20201203_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Dp',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Points',
            field=models.IntegerField(default=0),
        ),
    ]
