# Generated by Django 3.1.4 on 2020-12-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkxmain', '0003_auto_20201204_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Notifications',
            field=models.JSONField(null=True),
        ),
    ]
