# Generated by Django 3.1.4 on 2020-12-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkxmain', '0005_auto_20201204_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bio',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Notifications',
            field=models.JSONField(default='{}', null=True),
        ),
    ]
