# Generated by Django 3.1.4 on 2020-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkxmain', '0006_auto_20201204_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='Notifications',
            field=models.JSONField(blank=True, default='{}'),
        ),
    ]
