# Generated by Django 3.1.4 on 2020-12-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkxmain', '0007_auto_20201204_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Dp',
            field=models.ImageField(upload_to='static/DPs'),
        ),
    ]
