# Generated by Django 3.1.4 on 2020-12-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkxmain', '0009_auto_20201204_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Followers',
            field=models.JSONField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='user',
            name='Following',
            field=models.JSONField(blank=True, default='{}'),
        ),
    ]
