# Generated by Django 3.1.4 on 2020-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkxmain', '0011_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Dp',
            field=models.ImageField(default='static/images/profileicon.png', upload_to='DPs'),
        ),
    ]
