# Generated by Django 3.1.4 on 2020-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkxmain', '0012_auto_20201204_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Postlist',
            field=models.JSONField(blank=True, default='{}'),
        ),
    ]
